# Generated by Django 5.2.4 on 2025-10-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytquiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
